Create approving requests view
CEN3031-10A/mean pull request #10
Opened 2017-10-03 03:03 UTC by kevdaci

## Commit Message Guidelines
```
Header
Blank Line
Body
Blank Line
Footer

The header should look like:
<type>(<scope>): <subject>

The body should have any necessary detailed info about the commit:
An example, references as to where this idea came from, etc.

The footer should have all the issues tagged:
Fixes #123, Fixes #456

So a commit should look like:
feat(users): Add new Yahoo authentication

Yahoo authentication idea proposed by @codydaig
Example implementation in file.js

Fixes #82
```

* Types: 
  * feat - Features, Enhancements, and overall Improvements
  * fix - Fixes, Bugs, HotFixs, etc...
  * doc - Changes to the Documentation and doesn't actually touch any code.
* Scope:
  * The scope should be where the change took place.
  * Examples: users, core, config, articles
* Subject:
  * The subject line should be clear and concise as to what is being accomplished in the commit.
* General Rules:
  * No Line in the Commit message can be longer than 80 characters.
* Reference: [Angular Conventions](https://github.com/ajoslin/conventional-changelog/blob/master/conventions/angular.md)

2017-10-03 21:21 UTC, RyanClementsHax commented on modules/users/client/views/admin/view-applicants.html
> +    <table class="table table-hover" style="text-align:center; vertical-align: middle">
styles should be done via css instead of inline styles like this

2017-10-03 21:21 UTC, RyanClementsHax commented on modules/users/client/views/admin/view-applicants.html
> +      <div class="col-md-4" style="margin-top: 2em">
same as below

2017-10-03 21:21 UTC, RyanClementsHax commented on modules/users/client/views/admin/view-applicants.html
> +<section style="padding:20px">
same as below

2017-10-03 21:21 UTC, RyanClementsHax commented on modules/users/client/views/admin/view-applicants.html
> +                  Fill in the rest of the table:
delete this comment

2017-10-03 21:22 UTC, RyanClementsHax commented on modules/users/client/views/admin/view-applicants.html
> +                      <input type="checkbox"  class="approve" name="approve[1][]" value="1">
I think the name attribute is uneccessary

2017-10-03 21:23 UTC, RyanClementsHax commented on modules/users/client/views/admin/view-applicants.html
> +<script type="text/javascript">
remove all of this javascript and move it into the controller files

2017-10-03 21:23 UTC, RyanClementsHax commented on modules/users/client/views/admin/view-applicants.html
> +<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
these links and scripts are unecessary

2017-10-03 21:24 UTC, RyanClementsHax commented
Overall:
Make sure that you create views like the other modules do. They have a view and controller hooked up to the router.

2017-10-03 21:37 UTC, RyanClementsHax commented on modules/users/client/views/admin/view-applicants.html
> +                <tr class="other-rows">
make sure these are defined

2017-10-03 21:37 UTC, RyanClementsHax commented on modules/users/client/views/admin/view-applicants.html
> +              <thead>
look at how the admin users page does this

2017-10-03 21:37 UTC, RyanClementsHax commented on modules/users/client/views/admin/view-applicants.html
> +  <uib-pagination boundary-links="true" max-size="8" items-per-page="vm.itemsPerPage" total-items="vm.filterLength" ng-model="vm.currentPage" ng-change="vm.pageChanged()"></uib-pagination>
double check if this is necessary

2017-10-03 21:37 UTC, RyanClementsHax commented on modules/users/client/views/admin/view-applicants.html
> +  $("input:checkbox").on('click', function() {
ng-click="vm.functionName()"

2017-10-08 20:53 UTC, RyanClementsHax requested changes

2017-10-08 20:53 UTC, RyanClementsHax commented on modules/users/client/controllers/admin/view-applicants.client.controller.js
> +        'approved': false,
make sure that these objects are in line with the user model that we created. Also, approved and declined should be wrapped into one status

2017-10-08 20:53 UTC, RyanClementsHax commented on modules/users/client/controllers/admin/view-applicants.client.controller.js
> +      if (applicant.declined)
can simplify to:
applicant.declined = !applicant.declined

2017-10-08 20:53 UTC, RyanClementsHax commented on modules/users/client/controllers/admin/view-applicants.client.controller.js
> +    vm.changeApproveState = function (applicant) {
same as above comment

2017-10-10 15:52 UTC, RyanClementsHax requested changes
This pull request is unfinished because it does not include the functionality to approve an applicant

2017-10-10 15:52 UTC, RyanClementsHax commented on modules/users/server/routes/admin.server.routes.js
> +    //.delete(adminPolicy.isAllowed, admin.deleteUnapprovedUser);
should not commit commented out code

2017-10-21 18:56 UTC, markd315 commented
This can be closed because my new pull request includes these commits and extends their functionality.

2017-10-21 18:56 UTC, closed without merging